# Generated by Django 4.1.4 on 2023-11-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_activityandstudent_cargo_feu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(default='/media/store/sin-photo.jpg', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actividades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activityandstudent')),
            ],
            options={
                'verbose_name': 'multimedia',
                'verbose_name_plural': 'multimedias',
            },
        ),
    ]
