# Generated by Django 4.1.4 on 2023-10-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('month', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=4)),
                ('in_production', models.CharField(max_length=1)),
                ('is_investigation', models.CharField(max_length=1)),
                ('deporte', models.CharField(max_length=1)),
                ('guardia', models.CharField(max_length=1)),
                ('cultura', models.CharField(max_length=1)),
                ('residencia', models.CharField(max_length=1)),
                ('tsu', models.CharField(max_length=1)),
                ('feu_ujc', models.CharField(max_length=1)),
                ('premio_mella', models.BooleanField(default=False)),
                ('titulo_oro', models.BooleanField(default=False)),
                ('menos_graves', models.IntegerField(default=0)),
                ('graves', models.IntegerField(default=0)),
                ('muy_graves', models.IntegerField(default=0)),
                ('is_repitente', models.BooleanField(default=False)),
                ('arrastre', models.IntegerField(default=0)),
                ('mundial', models.IntegerField(default=0)),
                ('index_academico', models.FloatField(default=0)),
                ('other_indicator', models.FloatField(default=0)),
                ('valor_final', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
