# Generated by Django 4.1.4 on 2023-10-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_academy_year_alter_profile_carrera_and_more'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityAndStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(blank=True, default=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='aspecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aspecto'),
        ),
        migrations.AddField(
            model_name='activity',
            name='profiles',
            field=models.ManyToManyField(through='app.ActivityAndStudent', to='authentication.profile'),
        ),
    ]
