# Generated by Django 4.1.4 on 2023-10-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aspecto_remove_activity_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='month',
            field=models.IntegerField(blank=True, choices=[(0, '--'), (1, 'enero'), (2, 'febrero'), (3, 'marzo'), (4, 'abril'), (5, 'mayo'), (6, 'junio'), (7, 'julio'), (8, 'agosto'), (9, 'septiembre'), (10, 'octubre'), (11, 'noviembre'), (12, 'diciembre')], default=0, null=True),
        ),
    ]
