# Generated by Django 4.1.4 on 2023-11-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_activity_aspecto_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='cargo_feu',
            field=models.IntegerField(blank=True, choices=[(1, 'Presidente'), (2, 'Vice-Presidente'), (3, 'Activista de Alta'), (4, 'Organizador'), (5, 'Ideologico'), (6, 'Cultura'), (7, 'Deporte'), (8, 'Comunicacion'), (9, 'Atension a planteamientos'), (10, 'Atension al becario'), (11, 'Investigacion'), (12, 'Docencia')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='cargo_ujc',
            field=models.IntegerField(blank=True, choices=[(1, 'Presidente'), (2, 'Vice-Presidente'), (3, 'Activista de Alta'), (4, 'Organizador'), (5, 'Ideologico'), (6, 'Cultura'), (7, 'Deporte'), (8, 'Comunicacion'), (9, 'Atension a planteamientos'), (10, 'Atension al becario'), (11, 'Investigacion'), (12, 'Docencia')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='comite_base',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='distincion_fututo_maestro',
            field=models.BooleanField(blank=True, help_text='Este se refiere a la distincion del Futuro Maestro', null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='distincion_joven',
            field=models.BooleanField(blank=True, help_text='Este campo se refiere a la distinsion Joven 20 Aniversario de la FEU', null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='distincion_marzo',
            field=models.BooleanField(blank=True, help_text='Este se refiere a la distincion 13 de Marzo', null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='es_feu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='es_ujc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='evaluacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Bien'), (2, 'Regular'), (3, 'Mal')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='has_investigacion',
            field=models.BooleanField(blank=True, help_text='Si pertence o no a una linea de investigacion', null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='has_publicacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='has_roles',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='is_ayudante',
            field=models.BooleanField(blank=True, help_text="Este campo se refiere a que si el alumno fue 'alumno ayudante'", null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, 'Brigada'), (2, 'Facultad'), (3, 'Universidad')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel_alacanzado',
            field=models.IntegerField(blank=True, choices=[(1, 'Avanzado'), (2, 'Intermedio'), (3, 'Basico')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel_autor',
            field=models.IntegerField(blank=True, choices=[(1, '1er Autor'), (2, '2do Autor'), (2, '3er Autor')], help_text="Esto es de 'Publicaciones logradas como autor o coautor'", null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel_evento',
            field=models.IntegerField(blank=True, choices=[(1, 'Nacionales'), (2, 'Internacionales')], help_text="Esto es de 'Pertenece a una linea de investigacion'", null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel_publicacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto')], help_text="Esto es de 'Publicaciones logradas como autor o coautor'", null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_publicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='participacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Capacitaciones'), (2, 'Despliegues'), (3, 'Exposicion de Resultado de la Produccion')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='roles',
            field=models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Analista'), (3, 'Programador'), (4, 'Jefe de Proyecto')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_evento', models.CharField(blank=True, help_text='Este campo almacena el nombre de ese evento colateral en que participa', max_length=255, null=True)),
                ('es_colateral', models.BooleanField(blank=True, default=False, null=True)),
                ('nivel', models.IntegerField(blank=True, choices=[(1, 'Facultad'), (2, 'Universidad'), (3, 'Provincial'), (4, 'Nacional'), (5, 'Internacional')], null=True)),
                ('result', models.IntegerField(blank=True, choices=[(1, '1er Lugar'), (2, '2do Lugar'), (3, '3er Lugar')], null=True)),
                ('actividades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activityandstudent')),
            ],
        ),
    ]
