# Generated by Django 4.1.4 on 2023-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_nivel_alacanzado_activityandstudent_nivel_alcanzado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='month',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='weight',
        ),
    ]
