# Generated by Django 4.1.4 on 2023-11-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_activity_month_remove_activity_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description',
            new_name='name',
        ),
    ]
