# Generated by Django 4.1.4 on 2023-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_description_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='actividades_pid',
            field=models.IntegerField(blank=True, choices=[(1, 'Ferias'), (2, 'Despliegues'), (3, 'Otras Actividades de la Produccion')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='grupo_edu_amor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='other_reconocimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='rol',
            field=models.CharField(blank=True, help_text='Area donde has realizado la PID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='where_pid',
            field=models.CharField(blank=True, help_text='Area donde has realizado la PID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='with_arrastres',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='with_mundiales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='with_repitencias',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('actividades', models.ManyToManyField(to='app.activityandstudent')),
            ],
        ),
    ]
