# Generated by Django 4.1.4 on 2023-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_asignatura_actividades_asignatura_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='asignatura_ayudante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
