# Generated by Django 4.1.4 on 2023-11-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_academy_year_alter_profile_carrera_and_more'),
        ('app', '0014_activityandstudent_asignatura_ayudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activity'),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
    ]
