# Generated by Django 4.1.4 on 2023-11-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_activityandstudent_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='student',
        ),
    ]
