# Generated by Django 4.1.4 on 2023-11-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_asignatura_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='asignaturas_ayudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asignatura'),
        ),
    ]
