# Generated by Django 4.1.4 on 2023-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_activityandstudent_asignaturas_ayudante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='cantidad_repitencias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
