# Generated by Django 4.1.4 on 2023-11-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_activityandstudent_cantidad_repitencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='other_reconocimiento',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
