# Generated by Django 4.1.4 on 2023-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_activityandstudent_other_reconocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nombre_sub_evento',
            field=models.IntegerField(blank=True, choices=[(1, 'Copa de Ingeniera de Software'), (2, 'Copa de Base de Datos'), (3, 'Copa Pascal'), (4, 'Mi web por Cuba'), (5, 'Olimpiada de Matematica')], null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre_evento',
            field=models.IntegerField(blank=True, choices=[(1, 'Forum de Historia'), (2, 'Seminario Juvenil MArtiano'), (3, 'Olimpiada de Idiomas'), (4, 'Jornada de Ingeniro en Ciencias Informaticas'), (5, 'Jornada Cientifica Estudiantil'), (6, 'Peña Tecnologica')], null=True),
        ),
    ]
