# Generated by Django 4.1.4 on 2023-11-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_evento_nombre_sub_evento_alter_evento_nombre_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='nombre',
        ),
    ]
