# Generated by Django 4.1.4 on 2023-11-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_evento_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityandstudent',
            old_name='es_feu',
            new_name='es_colateral',
        ),
        migrations.RenameField(
            model_name='activityandstudent',
            old_name='es_ujc',
            new_name='is_evento',
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_evento',
            field=models.IntegerField(blank=True, choices=[(1, 'Forum de Historia'), (2, 'Seminario Juvenil MArtiano'), (3, 'Olimpiada de Idiomas'), (4, 'Jornada de Ingeniro en Ciencias Informaticas'), (5, 'Jornada Cientifica Estudiantil'), (6, 'Peña Tecnologica')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_evento_colateral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_sub_evento',
            field=models.IntegerField(blank=True, choices=[(1, 'Copa de Ingeniera de Software'), (2, 'Copa de Base de Datos'), (3, 'Copa Pascal'), (4, 'Mi web por Cuba'), (5, 'Olimpiada de Matematica')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='organizacion',
            field=models.IntegerField(blank=True, choices=[(1, 'FEU'), (2, 'UJC')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, 'Relevante'), (2, 'Destacado'), (3, 'Mencion'), (4, 'Participacion')], null=True),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, 'Facultad'), (2, 'Universidad'), (3, 'Provincial'), (4, 'Nacional'), (5, 'Internacional')], null=True),
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
