# Generated by Django 4.1.4 on 2023-11-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_activityandstudent_actividad_participado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='cantidad_senalamiento_guardia_estudiantil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='deporte',
            field=models.IntegerField(blank=True, choices=[(1, 'Ajedrez'), (2, 'Atletismo'), (3, 'Carrera de Orientacion'), (4, 'Baloncesto'), (5, 'Balonmano'), (6, 'Boxeo'), (7, 'Futbol Sala'), (8, 'Futbol 11'), (9, 'Natacion'), (10, 'Tenis'), (11, 'Pelota'), (12, 'Softball'), (13, 'Voleyball'), (14, 'Voleyball Playa'), (15, 'Yudo'), (16, 'Karate'), (17, 'Taewondo'), (18, 'Taewondo'), (19, 'Cubalon'), (20, 'Maraton'), (21, 'DOTA')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_actividades_limpieza_areas_comunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_bk_mas_bonita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_copas_mundialess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_jjmm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_marabana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_participacion_actos_matutinos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_participacion_festivales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_senalamiento_guardia_estudiantil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='if_senalamiento_residencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='lugar',
            field=models.IntegerField(blank=True, choices=[(1, 'Universidad'), (2, 'Juegos Provinciales Giraldillos'), (3, 'Juegos Nacionales')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='lugar_copas_mundiales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='lugar_dnd_realizo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='manifestacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='mes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nivel_artista_aficionado',
            field=models.IntegerField(blank=True, choices=[(1, 'Facultad'), (2, 'Provincial'), (3, 'Nacional')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_actividad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_actividades_limpieza_areas_comunes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_evento_copas_mundiales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_evento_marabana',
            field=models.IntegerField(blank=True, choices=[(1, 'MaraCuba'), (2, 'MaraHabana'), (3, 'Cacahual'), (5, 'Maratón por el Día Olímpico'), (4, 'Maratón Terry Fox'), (6, 'Maratón 10 de Octubre')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='premio_artista_aficionado',
            field=models.IntegerField(blank=True, choices=[(1, 'Oro'), (2, 'Plata'), (3, 'Bronce'), (4, 'Mencion')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='reconocimiento_otorgado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='responsabilidad',
            field=models.IntegerField(blank=True, choices=[(1, 'Jefe de Edificio'), (2, 'Jefe de Apartamento'), (3, 'Ninguna')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='resultado_actividades_limpieza_areas_comunes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='resultado_deporte',
            field=models.IntegerField(blank=True, choices=[(1, 'Oro'), (2, 'Plata'), (3, 'Bronce'), (4, 'Participacion')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='total_ausencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='total_ausencias_injustificadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='total_ausencias_justificadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='total_recuperadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cuarteleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluacion', models.IntegerField(blank=True, choices=[(1, 'Excelente'), (2, 'Bien'), (3, 'Regular'), (4, 'Mal')], null=True)),
                ('activity_and_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activityandstudent')),
            ],
        ),
    ]
