# Generated by Django 4.1.4 on 2023-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_activityandstudent_cantidad_senalamiento_guardia_estudiantil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityandstudent',
            old_name='manifestacion',
            new_name='manifestacion_actividad_facultad',
        ),
        migrations.RenameField(
            model_name='activityandstudent',
            old_name='nombre_actividad',
            new_name='manifestacion_festivales',
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_actividad_facultad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
