# Generated by Django 4.1.4 on 2023-11-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_manifestacion_activityandstudent_manifestacion_actividad_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='deporte',
            field=models.CharField(blank=True, choices=[(1, 'Ajedrez'), (2, 'Atletismo'), (3, 'Carrera de Orientacion'), (4, 'Baloncesto'), (5, 'Balonmano'), (6, 'Boxeo'), (7, 'Futbol Sala'), (8, 'Futbol 11'), (9, 'Natacion'), (10, 'Tenis'), (11, 'Pelota'), (12, 'Softball'), (13, 'Voleyball'), (14, 'Voleyball Playa'), (15, 'Yudo'), (16, 'Karate'), (17, 'Taewondo'), (18, 'Taewondo'), (19, 'Cubalon'), (20, 'Maraton'), (21, 'DOTA')], max_length=255, null=True),
        ),
    ]
