# Generated by Django 4.1.4 on 2023-11-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_activityandstudent_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuarteleria',
            name='activity_and_student',
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='cuartelerias',
            field=models.ManyToManyField(to='app.cuarteleria'),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='resultado_copas_mundiales',
            field=models.IntegerField(blank=True, choices=[(1, 'Oro'), (2, 'Plata'), (3, 'Bronce'), (4, 'Participacion')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='resultado_evento_marabana',
            field=models.IntegerField(blank=True, choices=[(1, 'Oro'), (2, 'Plata'), (3, 'Bronce'), (4, 'Participacion')], null=True),
        ),
    ]
