# Generated by Django 4.1.4 on 2023-11-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_cuarteleria_activity_and_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='evaluacion_cuarteleria',
            field=models.CharField(blank=True, choices=[(1, 'MaraCuba'), (2, 'MaraHabana'), (3, 'Cacahual'), (5, 'Maratón por el Día Olímpico'), (4, 'Maratón Terry Fox'), (6, 'Maratón 10 de Octubre')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='activityandstudent',
            name='cuartelerias',
        ),
        migrations.DeleteModel(
            name='Cuarteleria',
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='cuartelerias',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
