# Generated by Django 4.1.4 on 2023-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_activityandstudent_evaluacion_cuarteleria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityandstudent',
            name='funsion_desempenada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='motivo_sancion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_distincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='nombre_mision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='organismo_otorga_distincion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='proceso',
            field=models.IntegerField(blank=True, choices=[(1, 'Cumplido'), (2, 'En Cumplimiento')], null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='sanciones_o_medida',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='senalamiento_curso',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
