# Generated by Django 4.1.4 on 2023-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_activityandstudent_funsion_desempenada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='deporte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
