# Generated by Django 4.1.4 on 2023-11-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_activityandstudent_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='resultado_deporte',
            field=models.CharField(blank=True, choices=[(1, 'Oro'), (2, 'Plata'), (3, 'Bronce'), (4, 'Participacion')], max_length=255, null=True),
        ),
    ]
