# Generated by Django 4.1.4 on 2023-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_activityandstudent_resultado_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityandstudent',
            name='if_participacion_actos_matutinos',
        ),
        migrations.AddField(
            model_name='activityandstudent',
            name='actividades_participacion_actos_matutinos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
