# Generated by Django 4.1.4 on 2023-11-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_activityandstudent_deporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='nivel',
            field=models.CharField(blank=True, choices=[(1, 'Facultad'), (2, 'Universidad'), (3, 'Provincial'), (4, 'Nacional'), (5, 'Internacional')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='nombre_evento',
            field=models.CharField(blank=True, choices=[(1, 'Forum de Historia'), (2, 'Seminario Juvenil MArtiano'), (3, 'Olimpiada de Idiomas'), (4, 'Jornada de Ingeniero en Ciencias Informaticas'), (5, 'Jornada Cientifica Estudiantil'), (6, 'Peña Tecnologica')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='nombre_sub_evento',
            field=models.CharField(blank=True, choices=[(1, 'Copa de Ingeniera de Software'), (2, 'Copa de Base de Datos'), (3, 'Copa Pascal'), (4, 'Mi web por Cuba'), (5, 'Olimpiada de Matematica')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='result',
            field=models.CharField(blank=True, choices=[(1, 'Relevante'), (2, 'Destacado'), (3, 'Mencion'), (4, 'Participacion')], max_length=255, null=True),
        ),
    ]
