# Generated by Django 4.1.4 on 2023-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_activityandstudent_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityandstudent',
            name='nombre_evento',
            field=models.CharField(blank=True, choices=[(1, 'Forum de Historia'), (2, 'Seminario Juvenil Martiano'), (3, 'Olimpiada de Idiomas'), (4, 'Jornada de Ingeniero en Ciencias Informaticas'), (5, 'Jornada Cientifica Estudiantil'), (6, 'Peña Tecnologica')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityandstudent',
            name='roles',
            field=models.CharField(blank=True, choices=[(1, 'Administrador'), (2, 'Analista'), (3, 'Programador'), (4, 'Jefe de Proyecto')], max_length=255, null=True),
        ),
    ]
