# Generated by Django 4.1.4 on 2023-12-03 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0041_alter_activityandstudent_evaluacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracterizacion',
            new_name='Integralidad',
        ),
    ]
