# Generated by Django 4.1.4 on 2023-12-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_caracterizacion_integralidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralidad',
            name='cultura',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='deporte',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='fac',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='feu_ujc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='guardia',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='in_production',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='is_investigation',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='premio_mella',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='residencia',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='titulo_oro',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='integralidad',
            name='tsu',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
