# Generated by Django 4.1.4 on 2023-10-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academy_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grupo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_exp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol_fac',
            field=models.IntegerField(blank=True, choices=[(1, 'estudiante'), (2, 'profesor guia'), (3, 'profesor de año'), (4, 'vicedecana/o')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol_universitario',
            field=models.IntegerField(blank=True, choices=[(1, 'estudiante'), (2, 'profesor'), (3, 'vicedecana/o')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solapin',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
